FROM python:3.8-slim AS build-env

RUN apt-get update && \
    apt-get install -y \
    apache2 \
    curl \
    git && \
    rm -rf /var/lib/apt/lists/*

ADD . /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.8-slim
COPY --from=build-env /app /app
WORKDIR /app
ENTRYPOINT ["python", "hello.py"]